### ISSUE TITLE
Cannot find bridges on iOS

### ISSUE THREAD

**Issue by anas10** [PhilipsHue/HueSDK#38]
Hello,

I am using the current sdk (bdbf00f2f95a14f20e8d74a2acfd1e67d5b8cbb9) on this repository.

When I do a search for the bridges using the SDK I do not get any results : 

```
let bridgeDiscovery: PHSBridgeDiscovery = PHSBridgeDiscovery()
[..]
bridgeDiscovery
            .search([.discoveryOptionUPNP, .discoveryOptionNUPNP]) { (results, returnCode) in
                // Results are empty
        }
```

However, if I go here `https://www.meethue.com/api/nupnp` I can see the bridge and it works when I access directly using the IP.

PS: Search by iPScan doesn't return any results either.

Any idea?

**Comment by smiLLe** [comment]
Yea, i am having the same problem as a lot of other people. They tell you to get the EDK because this repo is deprecated. To get the new EDK you have to register on their website until they accept you (i  am waiting for almost 3 weeks now).
Good luck
https://developers.meethue.com/content/edk-terms-use

**Comment by jhvdb87** [comment]
@smiLLe I will contact my colleague to check your registration !

**Comment by anas10** [comment]
@jhvdb87 I actually registered to get the new EDK as well around 3 weeks ago too.

**Comment by jhvdb87** [comment]
Can you all please contact through philipshuedev@philips.com, so they will check your registration.
